(function(global){
  'use strict';
  const C=global.PCGDCore;
  if(!C||!global.PCGDEngine) throw new Error('PCGD core chưa được tải.');
  const {COL,s,n,norm,nonblank,eq,pct,schoolYear,canonicalLevel,isFemale,isMinority,canLearn,currentSchool,gradAtLeastTH,gradAtLeastTHCS,byVillage,count,groupAge,ageMetrics}=C;
  function reportMN1(result){
    const ages=[0,1,2,3,4,5,6],years=ages.map(a=>result.year-a),rs=result.records;
    const rows=[['THỐNG KÊ TRẺ EM 0 ĐẾN 5 TUỔI PCGDMN CHO TRẺ EM 5 TUỔI'],[`Năm điều tra: ${result.year}`],[],['Chỉ tiêu',...ages.map(a=>`${a} tuổi`),'Tổng 0-5'],['Năm sinh',...years,'']];
    const metric=(label,fn)=>{const vals=ages.map(a=>fn(ageMetrics(rs,a)));rows.push([label,...vals,vals.slice(0,6).reduce((x,y)=>x+y,0)])};
    metric('Tổng số trẻ trong độ tuổi',x=>x.total);metric('Trẻ em gái',x=>x.female);metric('Trẻ dân tộc thiểu số',x=>x.minority);metric('Trẻ khuyết tật',x=>x.dis);metric('Khuyết tật có khả năng học tập',x=>x.capable);metric('Khuyết tật được tiếp cận giáo dục',x=>x.access);
    const enrolled=ages.map(a=>count(rs,r=>r.age===a&&r.bh==='MN'));rows.push(['Đang học mầm non',...enrolled,enrolled.slice(0,6).reduce((x,y)=>x+y,0)]);return rows;
  }
  function reportMN2(result){
    const rows=[['THỐNG KÊ PHỔ CẬP GIÁO DỤC MẦM NON CHO TRẺ EM 5 TUỔI'],[`Năm điều tra: ${result.year}`],[],['TT','Thôn/xóm','Trẻ 5 tuổi PPC','5 tuổi đến lớp','Tỉ lệ %','Trẻ 6 tuổi đã HT CTGDMN','Tỉ lệ %','KT độ tuổi MN','KT có khả năng HT','KT tiếp cận GD','Tỉ lệ %','Đội ngũ','CSVC','Gợi ý kết quả']];
    byVillage(result.records).forEach(([v,rs],i)=>{const a5=rs.filter(r=>r.age===5&&r.br!==1),a6=rs.filter(r=>r.age===6&&r.br!==1),go5=count(a5,r=>r.bh==='MN'),done6=count(a6,r=>canonicalLevel(r.raw[COL.W])==='MN'),dis=rs.filter(r=>r.bf==='MN'&&r.br===1),cap=count(dis,canLearn),acc=count(dis,r=>canLearn(r)&&currentSchool(r));const p5=pct(go5,a5.length),p6=pct(done6,a6.length);rows.push([i+1,v,a5.length,go5,p5,done6,p6,dis.length,cap,acc,pct(acc,cap),'Cần bổ sung','Cần bổ sung',(p5>=95&&p6>=90)?'Đạt theo dữ liệu điều tra':'Chưa đạt theo dữ liệu điều tra'])});return rows;
  }
  function reportTH1(result){
    const ages=[6,7,8,9,10,11,12,13,14],rs=result.records;const rows=[['THỐNG KÊ TRẺ EM 6 ĐẾN 14 TUỔI PHỔ CẬP GIÁO DỤC TIỂU HỌC'],[`Năm điều tra: ${result.year}`],[],['Chỉ tiêu',...ages.map(a=>`${a} tuổi`),'Tổng 6-10','Tổng 11-14']];
    const add=(label,p)=>{const vals=ages.map(a=>count(rs,r=>r.age===a&&p(r)));rows.push([label,...vals,vals.slice(0,5).reduce((x,y)=>x+y,0),vals.slice(5).reduce((x,y)=>x+y,0)])};
    add('Tổng số',()=>true);add('Nữ',isFemale);add('Dân tộc thiểu số',isMinority);add('Khuyết tật',r=>r.br===1);add('KT có khả năng học tập',r=>r.br===1&&canLearn(r));add('KT được tiếp cận giáo dục',r=>r.br===1&&canLearn(r)&&currentSchool(r));add('Số phải phổ cập',r=>r.br!==1);add('Đang học tiểu học',r=>r.bh==='TH');add('Đã hoàn thành tiểu học',r=>gradAtLeastTH(r));for(let g=1;g<=5;g++)add(`Đang học lớp ${g}`,r=>r.bh==='TH'&&n(r.raw[COL.R])===g);return rows;
  }
  function thCompletion(r){return gradAtLeastTH(r)||r.bh==='THCS'||r.bh==='THPT'||n(r.raw[COL.R])>=6;}
  function reportTH2(result){
    const rows=[['THỐNG KÊ PHỔ CẬP GIÁO DỤC TIỂU HỌC'],[`Năm điều tra: ${result.year}`],[],['TT','Thôn/xóm','HS 6-14','Khuyết tật','Trẻ 6 tuổi','6 tuổi vào lớp 1','Tỉ lệ %','Trẻ 11 tuổi','11 tuổi HTCTTH','Tỉ lệ %','Trẻ đến 14 tuổi','Đến 14 tuổi HTCTTH','Tỉ lệ %','KT','KT có khả năng HT','KT tiếp cận GD','Tỉ lệ %','Đội ngũ','CSVC','Gợi ý mức']];
    byVillage(result.records).forEach(([v,rs],i)=>{const school=groupAge(rs,6,14),a6=rs.filter(r=>r.age===6&&r.br!==1),in1=count(a6,r=>n(r.raw[COL.R])===1&&r.bh==='TH'),a11=rs.filter(r=>r.age===11&&r.br!==1),d11=count(a11,thCompletion),a14=rs.filter(r=>r.age>=11&&r.age<=14&&r.br!==1),d14=count(a14,thCompletion),dis=groupAge(rs,6,14).filter(r=>r.br===1),cap=count(dis,canLearn),acc=count(dis,r=>canLearn(r)&&currentSchool(r));const p6=pct(in1,a6.length),p11=pct(d11,a11.length),p14=pct(d14,a14.length);let level='';if(p6>=98&&p11>=90&&p14>=95)level='Gợi ý Mức 3';else if(p6>=95&&p11>=80&&p14>=90)level='Gợi ý Mức 2';else if(p6>=90)level='Gợi ý Mức 1';else level='Chưa đạt';rows.push([i+1,v,school.length,count(school,r=>r.br===1),a6.length,in1,p6,a11.length,d11,p11,a14.length,d14,p14,dis.length,cap,acc,pct(acc,cap),'Cần bổ sung','Cần bổ sung',level])});return rows;
  }
  function reportTHCS1(result){
    const ages=[11,12,13,14,15,16,17,18],rs=result.records;const rows=[['THỐNG KÊ THANH THIẾU NIÊN PHỔ CẬP GIÁO DỤC TRUNG HỌC CƠ SỞ'],[`Năm điều tra: ${result.year}`],[],['Chỉ tiêu',...ages.map(a=>`${a} tuổi`),'Tổng 15-18']];
    const add=(label,p)=>{const vals=ages.map(a=>count(rs,r=>r.age===a&&p(r)));rows.push([label,...vals,vals.slice(4).reduce((x,y)=>x+y,0)])};
    add('Tổng số',()=>true);add('Nữ',isFemale);add('Dân tộc thiểu số',isMinority);add('Khuyết tật',r=>r.br===1);add('KT có khả năng HT',r=>r.br===1&&canLearn(r));add('KT tiếp cận GD',r=>r.br===1&&canLearn(r)&&currentSchool(r));add('15-18 đã TN THCS',r=>r.bi==='TNC2');add('15-18 đã/đang học THPT-GDTX-GDNN',r=>nonblank(r.bj));return rows;
  }
  function reportTHCS21(result){
    const rows=[['BIỂU TỔNG HỢP KẾT QUẢ HUY ĐỘNG PHỔ CẬP GIÁO DỤC TRUNG HỌC CƠ SỞ'],[`Năm điều tra: ${result.year}`],[],['TT','Thôn/xóm','Trẻ 6 tuổi','Vào lớp 1','Tỷ lệ %','TN TH năm vừa qua','Vào lớp 6','Tỷ lệ %','11-14 tuổi','HTCT TH','Tỷ lệ %','15-18 tuổi','TN THCS','Tỷ lệ %','15-18 đã/đang học THPT-GDTX-GDNN','Tỷ lệ %','Gợi ý mức']];
    byVillage(result.records).forEach(([v,rs],i)=>{const a6=rs.filter(r=>r.age===6&&r.br!==1),in1=count(a6,r=>r.bh==='TH'&&n(r.raw[COL.R])===1),prev=schoolYear(result.year),tnTH=rs.filter(r=>canonicalLevel(r.raw[COL.W])==='TH'&&s(r.raw[COL.Y])===prev),in6=count(tnTH,r=>r.bh==='THCS'&&n(r.raw[COL.R])===6),a1114=groupAge(rs,11,14).filter(r=>r.br!==1),doneTH=count(a1114,thCompletion),a1518=groupAge(rs,15,18).filter(r=>r.br!==1),tnC2=count(a1518,r=>r.bi==='TNC2'),progress=count(a1518,r=>r.bi==='TNC2'&&nonblank(r.bj)),rTN=pct(tnC2,a1518.length),rProg=pct(progress,tnC2);let level=rTN>=95&&rProg>=80?'Gợi ý Mức 3':rTN>=90?'Gợi ý Mức 2':rTN>=80?'Gợi ý Mức 1':'Chưa đạt';rows.push([i+1,v,a6.length,in1,pct(in1,a6.length),tnTH.length,in6,pct(in6,tnTH.length),a1114.length,doneTH,pct(doneTH,a1114.length),a1518.length,tnC2,rTN,progress,rProg,level])});return rows;
  }
  function reportTHCS22(result){
    const rows=[['THỐNG KÊ PHỔ CẬP GIÁO DỤC TRUNG HỌC CƠ SỞ'],[`Năm điều tra: ${result.year}`],[],['TT','Thôn/xóm','TTN 11-18','Khuyết tật','TTN 15-18 TN THCS','Tỉ lệ %','15-18 đã/đang học THPT-GDTX-GDNN','Tỉ lệ %','KT 11-18','KT có khả năng HT','KT tiếp cận GD','Tỉ lệ %','Đội ngũ','CSVC','Gợi ý mức PC THCS']];
    byVillage(result.records).forEach(([v,rs],i)=>{const a1118=groupAge(rs,11,18),a1518=groupAge(rs,15,18).filter(r=>r.br!==1),tn=count(a1518,r=>r.bi==='TNC2'),pr=count(a1518,r=>r.bi==='TNC2'&&nonblank(r.bj)),dis=a1118.filter(r=>r.br===1),cap=count(dis,canLearn),acc=count(dis,r=>canLearn(r)&&currentSchool(r));const tr=pct(tn,a1518.length),pp=pct(pr,tn);let level=tr>=95&&pp>=80?'Gợi ý Mức 3':tr>=90?'Gợi ý Mức 2':tr>=80?'Gợi ý Mức 1':'Chưa đạt';rows.push([i+1,v,a1118.length,dis.length,tn,tr,pr,pp,dis.length,cap,acc,pct(acc,cap),'Cần bổ sung','Cần bổ sung',level])});return rows;
  }
  function literacyGroupRows(rs,label,min,max){const g=rs.filter(r=>r.age>=min&&r.age<=max&&r.br!==1),mc1=g.filter(r=>r.bo==='MC1'),mc2=g.filter(r=>r.bp==='MC2'),mc=g.filter(r=>r.bn==='MC'),re=g.filter(r=>n(r.raw[COL.AI])>0);return[label,g.length,count(g,isFemale),count(g,isMinority),mc1.length,count(mc1,isFemale),count(mc1,isMinority),mc2.length,count(mc2,isFemale),count(mc2,isMinority),mc.length,pct(mc.length,g.length),re.length,count(re,isFemale),count(re,isMinority)];}
  function reportCMC1(result){
    const rows=[['TỔNG HỢP TÌNH HÌNH SỐ LIỆU CÔNG TÁC XÓA MÙ CHỮ'],[`Năm điều tra: ${result.year}`],[],['TT','Thôn/xóm','DS 15-60','Nữ','Dân tộc','Nữ dân tộc','DS 15-25','Nữ','Dân tộc','Nữ dân tộc','MC1 15-25','Tỷ lệ %','Nữ MC1','Dân tộc MC1','MC2 15-25','Tỷ lệ %','Nữ MC2','Dân tộc MC2']];
    byVillage(result.records).forEach(([v,rs],i)=>{const g60=groupAge(rs,15,60).filter(r=>r.br!==1),g25=groupAge(rs,15,25).filter(r=>r.br!==1),m1=g25.filter(r=>r.bo==='MC1'),m2=g25.filter(r=>r.bp==='MC2');rows.push([i+1,v,g60.length,count(g60,isFemale),count(g60,isMinority),count(g60,r=>isFemale(r)&&isMinority(r)),g25.length,count(g25,isFemale),count(g25,isMinority),count(g25,r=>isFemale(r)&&isMinority(r)),m1.length,pct(m1.length,g25.length),count(m1,isFemale),count(m1,isMinority),m2.length,pct(m2.length,g25.length),count(m2,isFemale),count(m2,isMinority)])});return rows;
  }
  function reportCMC2(result){return[['THỐNG KÊ SỐ NGƯỜI MÙ CHỮ CÁC ĐỘ TUỔI'],[`Năm điều tra: ${result.year}`],[],['Nhóm tuổi','Dân số','Nữ','Dân tộc','MC mức 1','Nữ','Dân tộc','MC mức 2','Nữ','Dân tộc','Tổng MC','Tỷ lệ MC %','Tái mù chữ','Nữ','Dân tộc'],literacyGroupRows(result.records,'15 - 25 tuổi',15,25),literacyGroupRows(result.records,'26 - 35 tuổi',26,35),literacyGroupRows(result.records,'36 - 60 tuổi',36,60),literacyGroupRows(result.records,'Cộng 15 - 60',15,60)];}
  function reportCMC3(result){
    const rows=[['TỔNG HỢP KẾT QUẢ XÓA MÙ CHỮ'],[`Năm điều tra: ${result.year}`],[],['Độ tuổi','Năm sinh','Trong độ tuổi','Nữ','Dân tộc','Nữ dân tộc','MC1','Nữ','Dân tộc','Nữ dân tộc','MC2','Nữ','Dân tộc','Nữ dân tộc','Biết chữ','Nữ','Dân tộc','Nữ dân tộc','Tỷ lệ biết chữ %']];
    for(let age=15;age<=60;age++){const g=result.records.filter(r=>r.age===age&&r.br!==1),m1=g.filter(r=>r.bo==='MC1'),m2=g.filter(r=>r.bp==='MC2'),lit=g.filter(r=>r.bn!=='MC');rows.push([`${age} tuổi`,result.year-age,g.length,count(g,isFemale),count(g,isMinority),count(g,r=>isFemale(r)&&isMinority(r)),m1.length,count(m1,isFemale),count(m1,isMinority),count(m1,r=>isFemale(r)&&isMinority(r)),m2.length,count(m2,isFemale),count(m2,isMinority),count(m2,r=>isFemale(r)&&isMinority(r)),lit.length,count(lit,isFemale),count(lit,isMinority),count(lit,r=>isFemale(r)&&isMinority(r)),pct(lit.length,g.length)])}return rows;
  }
  function reportCMC4(result){
    const rows=[['THỐNG KÊ ĐẠT CHUẨN XÓA MÙ CHỮ'],[`Năm điều tra: ${result.year}`],[],['TT','Thôn/xóm','15-25 TS','Biết chữ MĐ1','Tỉ lệ %','Biết chữ MĐ2','Tỉ lệ %','15-35 TS','Biết chữ MĐ1','Tỉ lệ %','Biết chữ MĐ2','Tỉ lệ %','15-60 TS','Biết chữ MĐ1','Tỉ lệ %','Biết chữ MĐ2','Tỉ lệ %','Gợi ý mức']];
    byVillage(result.records).forEach(([v,rs],i)=>{const calc=(max)=>{const g=rs.filter(r=>r.age>=15&&r.age<=max&&r.br!==1),l1=g.filter(r=>r.bo!=='MC1'),l2=g.filter(r=>r.bo!=='MC1'&&r.bp!=='MC2');return[g.length,l1.length,pct(l1.length,g.length),l2.length,pct(l2.length,g.length)]};const a=calc(25),b=calc(35),c=calc(60);let level=(a[2]>=90&&b[4]>=90&&c[4]>=90)?'Gợi ý Mức 2':(a[2]>=90&&b[2]>=90&&c[2]>=90)?'Gợi ý Mức 1':'Chưa đạt';rows.push([i+1,v,...a,...b,...c,level])});return rows;
  }
  function manualSchoolSheet(title,level,kind,result){
    const schools=[...new Set(result.records.filter(r=>r.bh===level&&nonblank(r.schoolName)).map(r=>r.schoolName))].sort((a,b)=>a.localeCompare(b,'vi'));
    const rows=[[title],[`Năm điều tra: ${result.year}`],['LƯU Ý: Phiếu điều tra hộ dân không chứa đủ số liệu cơ sở vật chất/đội ngũ. Các cột dưới đây cần nhà trường bổ sung.'],[]];
    if(kind==='CSVC'){rows.push(['TT','Trường','Số lớp','Phòng học kiên cố','Phòng học bán kiên cố','Phòng tạm','Phòng chức năng','Thư viện','Thiết bị','Vệ sinh','Sân chơi/bãi tập','Ghi chú']);schools.forEach((x,i)=>rows.push([i+1,x,'','','','','','','','','','']))}else{rows.push(['TT','Trường','CBQL','Tổng GV','Biên chế','Hợp đồng','Nữ','Dân tộc','Trình độ đạt chuẩn','Tỉ lệ GV/lớp','Nhân viên','Ghi chú']);schools.forEach((x,i)=>rows.push([i+1,x,'','','','','','','','','','']))}
    if(!schools.length)rows.push(['','Chưa nhận diện tên trường từ phiếu điều tra. Hãy bổ sung thủ công.']);return rows;
  }
  function dataRows(result){
    const headers=['Thôn/xóm','TT','Họ đệm','Tên','Ngày','Tháng','Năm sinh','Nữ','Dân tộc','Tôn giáo','Diện ưu tiên','Họ đệm chủ hộ','Tên chủ hộ','Địa chỉ','Số phiếu','Diện cư trú','Tình trạng cư trú','Khối học','Lớp học','Quận/Huyện đang học','Tên trường','Mã trường','Bậc tốt nghiệp','Bổ túc','Năm tốt nghiệp','Bậc TN nghề','Số bằng','Năm TN nghề','Học xong lớp','Năm học xong','Bỏ học lớp','Năm bỏ học','Đang học lớp XMC','Hoàn thành lớp XMC','Tái mù chữ mức','KT vận động','KT nghe nói','KT nhìn','KT thần kinh/tâm thần','KT trí tuệ','KT học tập','Tự kỷ','KT khác','Có CN khuyết tật','Khả năng học tập','Hoàn cảnh đặc biệt','Chi tiết hoàn cảnh','Quan hệ chủ hộ','Họ tên cha/mẹ','Điện thoại','Ghi chú','','Hệ học','Lỗi mã trường','Tuổi','Load thôn','Load số phiếu','Lứa tuổi học','Làn tuổi','Đang học','15-18 TN THCS','Đã/đang học THPT-GDTX-GDNN','Tại chỗ','Học xong/bỏ lớp 9','Làn tuổi XMC','Mù chữ','MC mức 1','MC mức 2','Bỏ học','Khuyết tật','TN năm trước','Lưu ban','2 buổi/ngày'],rows=[headers];
    result.records.forEach(r=>{const x=Array(73).fill('');for(let c=0;c<=COL.AY;c++)x[c]=r.raw[c]??'';x[COL.BA]=r.ba;x[COL.BB]=r.bb;x[COL.BC]=r.bc;x[COL.BD]=r.bd;x[COL.BE]=r.be;x[COL.BF]=r.bf;x[COL.BG]=r.bg;x[COL.BH]=r.bh;x[COL.BI]=r.bi;x[COL.BJ]=r.bj;x[COL.BK]=r.bk;x[COL.BL]=r.bl;x[COL.BM]=r.bm;x[COL.BN]=r.bn;x[COL.BO]=r.bo;x[COL.BP]=r.bp;x[COL.BQ]=r.bq;x[COL.BR]=r.br;x[COL.BS]=r.bs;x[COL.BT]=r.bt;x[COL.BU]=r.bu;rows.push(x)});return rows;
  }
  function addSheet(wb,name,rows,widths){const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=(widths||rows[0]?.map((_,i)=>({wch:i===0?22:14}))||[]);XLSX.utils.book_append_sheet(wb,ws,name);}
  function exportResult(result,sourceName){
    const wb=XLSX.utils.book_new(),s0=result.summary,summary=[['PCGD–XMC SMART','BỘ KẾT QUẢ PHÂN TÍCH TỰ ĐỘNG'],['Năm điều tra',result.year],['Số file điều tra',s0.files],['Số thôn/xóm',s0.villages],['Nhân khẩu',s0.total],['Hộ/phiếu',s0.households],['15-18 tuổi (không KT)',s0.aged1518],['15-18 TN THCS',s0.tn1518],['Tỷ lệ TN THCS (%)',s0.rate1518],['15-60 tuổi mẫu XMC',s0.age1560],['Số gắn mù chữ',s0.mc1560],['Tỷ lệ không gắn mù chữ (%)',s0.notMcRate],['Khuyết tật',s0.disabilities],['Lỗi/cảnh báo',s0.issues],[],['Nguồn file','Loại','Số dòng','Năm trong file'],...result.sources.map(x=>[x.name,x.type,x.rows,x.fileYear||''])];
    addSheet(wb,'TongQuan',summary,[{wch:42},{wch:26},{wch:16},{wch:16}]);addSheet(wb,'SoatLoi',[['Mức độ','File nguồn','Dòng','Họ tên','Thôn/xóm','Nội dung','Gợi ý'],...result.issues.map(i=>[i.severity,i.sourceName,i.rowNumber,i.name,i.village,i.message,i.suggestion])],[{wch:10},{wch:28},{wch:9},{wch:28},{wch:24},{wch:55},{wch:55}]);addSheet(wb,'DATA',dataRows(result));
    addSheet(wb,'MN-1TE',reportMN1(result));addSheet(wb,'MN-2',reportMN2(result));addSheet(wb,'MN-CSVC',manualSchoolSheet('THỐNG KÊ CƠ SỞ VẬT CHẤT PCGDMN','MN','CSVC',result));addSheet(wb,'MN-ĐN',manualSchoolSheet('THỐNG KÊ ĐỘI NGŨ PCGDMN','MN','DN',result));
    addSheet(wb,'TH-1TE',reportTH1(result));addSheet(wb,'TH-2',reportTH2(result));addSheet(wb,'TH-CSVC',manualSchoolSheet('THỐNG KÊ CƠ SỞ VẬT CHẤT PCGD TIỂU HỌC','TH','CSVC',result));addSheet(wb,'TH-DN',manualSchoolSheet('THỐNG KÊ ĐỘI NGŨ PCGD TIỂU HỌC','TH','DN',result));
    addSheet(wb,'THCS-1TTN',reportTHCS1(result));addSheet(wb,'THCS-2.1',reportTHCS21(result));addSheet(wb,'THCS-2.2',reportTHCS22(result));addSheet(wb,'THCS-CSVC',manualSchoolSheet('THỐNG KÊ CƠ SỞ VẬT CHẤT PCGD THCS','THCS','CSVC',result));addSheet(wb,'THCS-DN',manualSchoolSheet('THỐNG KÊ ĐỘI NGŨ PCGD THCS','THCS','DN',result));
    addSheet(wb,'CMC-1',reportCMC1(result));addSheet(wb,'CMC-2',reportCMC2(result));addSheet(wb,'CMC-3',reportCMC3(result));addSheet(wb,'CMC-4',reportCMC4(result));
    const safe=(sourceName||'PCGDXMC').replace(/[\\/:*?"<>|]/g,'_').replace(/\.(xlsx?|xlsm)$/i,'');XLSX.writeFile(wb,`${safe}_TongHop_PCGDXMC_${result.year}.xlsx`,{compression:true});
  }
  global.PCGDEngine.exportResult=exportResult;
})(window);
